{% set name = "apply_defaults" %}
{% set version = "0.1.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 300e5495d0306f472c1aa34a522273e3066b9f50d3eb25cee17cd3b6177eea54

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  noarch: python

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - apply_defaults

about:
  home: https://github.com/bcb/apply_defaults
  license: MIT
  license_family: MIT
  license_file: https://github.com/bcb/apply_defaults/blob/master/LICENSE
  summary: Helps pull configuration into a project.
  doc_url:
  dev_url: https://github.com/bcb/apply_defaults

extra:
  recipe-maintainers:
    - bcb
